### ISSUE TITLE
Background image 

### ISSUE THREAD

**Issue by H-Punhan** [gullu-babashli/PragmatechFoundationProject#3]
https://github.com/gullu-babashli/PragmatechFoundationProject/blob/c9d353ddc7e4134c625294ad58c4ed2ca13b1bf0/Project/css/style.css#L3

Burada verdiyiniz şəkilini yolu yanlış-dır və dırnaq içində yazılmalıdır

**Comment by gullu-babashli** [comment]
Background image yerləşdirmək üçün daha düzgün variant nədir?
