### ISSUE TITLE
css

### ISSUE THREAD

**Issue by H-Punhan** [gullu-babashli/PragmatechFoundationProject#5]
https://github.com/gullu-babashli/PragmatechFoundationProject/blob/c9d353ddc7e4134c625294ad58c4ed2ca13b1bf0/Project/index.html#L15

belə bir css faylı yoxdur

**Comment by gullu-babashli** [comment]
Bu gələcəkdə istifadə üçün nəzərdə tutulmuşdu amma hələlik sildim, okay.
